Europe = {'Germany', 'Austria', 'Belgium', 'Cyprus', 'Estonia',
          'Finland', 'France', 'Greece', 'Ireland', 'Italy',
          'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands',
          'Portugal', 'Slovakia', 'Slovenia', 'Spain'}

all_codes = {'USD', 'AED', 'ARS', 'AUD', 'BGN', 'BRL',
             'BSD', 'CAD', 'CHF', 'CLP', 'CNY', 'COP',
             'CZK', 'DKK', 'DOP', 'EGP', 'EUR', 'FJD',
             'GBP', 'GTQ', 'HKD', 'HRK', 'HUF', 'IDR',
             'ILS', 'INR', 'ISK', 'JPY', 'KRW', 'KZT',
             'MXN', 'MYR', 'NOK', 'NZD', 'PAB', 'PEN',
             'PHP', 'PKR', 'PLN', 'PYG', 'RON', 'RUB',
             'SAR', 'SEK', 'SGD', 'THB', 'TRY', 'TWD', 
             'UAH', 'UYU', 'VND', 'ZAR'}
code_ref = [
        {'Currency Code': 'AED', 'Currency Name': 'UAE Dirham', 'Region': 'United Arab Emirates'},
        {'Currency Code': 'ARS', 'Currency Name': 'Argentine Peso', 'Region': 'Argentina'},
        {'Currency Code': 'AUD', 'Currency Name': 'Australian Dollar', 'Region': 'Australia'},
        {'Currency Code': 'BGN', 'Currency Name': 'Bulgarian Lev', 'Region': 'Bulgaria'},
        {'Currency Code': 'BRL', 'Currency Name': 'Brazilian Real', 'Region': 'Brazil'},
        {'Currency Code': 'BSD', 'Currency Name': 'Bahamian Dollar', 'Region': 'Bahamas'},
        {'Currency Code': 'CAD', 'Currency Name': 'Canadian Dollar', 'Region': 'Canada'},
        {'Currency Code': 'CHF', 'Currency Name': 'Swiss Franc', 'Region': 'Switzerland'},
        {'Currency Code': 'CLP', 'Currency Name': 'Chilean Peso', 'Region': 'Chile'},
        {'Currency Code': 'CNY', 'Currency Name': 'Chinese Renminbi', 'Region': 'China'},
        {'Currency Code': 'COP', 'Currency Name': 'Colombian Peso', 'Region': 'Colombia'},
        {'Currency Code': 'CZK', 'Currency Name': 'Czech Koruna', 'Region': 'Czech Republic'},
        {'Currency Code': 'DKK', 'Currency Name': 'Danish Krone', 'Region': 'Denmark'},
        {'Currency Code': 'DOP', 'Currency Name': 'Dominican Peso', 'Region': 'Dominican Republic'},
        {'Currency Code': 'EGP', 'Currency Name': 'Egyptian Pound', 'Region': 'Egypt'},
        {'Currency Code': 'EUR', 'Currency Name': 'Euro', 'Region': 'Europe'},
        {'Currency Code': 'FJD', 'Currency Name': 'Fiji Dollar', 'Region': 'Fiji'},
        {'Currency Code': 'GBP', 'Currency Name': 'Pound Sterling', 'Region': 'United Kingdom'},
        {'Currency Code': 'GTQ', 'Currency Name': 'Guatemalan Quetzal', 'Region': 'Guatemala'},
        {'Currency Code': 'HKD', 'Currency Name': 'Hong Kong Dollar', 'Region': 'Hong Kong'},
        {'Currency Code': 'HRK', 'Currency Name': 'Croatian Kuna', 'Region': 'Croatian'},
        {'Currency Code': 'HUF', 'Currency Name': 'Hungarian Forint', 'Region': 'Hungary'},
        {'Currency Code': 'IDR', 'Currency Name': 'Indonesian Rupiah', 'Region': 'Indonesia'},
        {'Currency Code': 'ILS', 'Currency Name': 'Israeli Shekel', 'Region': 'Israel'},
        {'Currency Code': 'INR', 'Currency Name': 'Indian Rupee', 'Region': 'India'},
        {'Currency Code': 'ISK', 'Currency Name': 'Icelandic Krona', 'Region': 'Iceland'},
        {'Currency Code': 'JPY', 'Currency Name': 'Japanese Yen', 'Region': 'Japan'},
        {'Currency Code': 'KRW', 'Currency Name': 'South Korean Won', 'Region': 'Korea'},
        {'Currency Code': 'KZT', 'Currency Name': 'Kazakhstani Tenge', 'Region': 'Kazakhstan'},
        {'Currency Code': 'MXN', 'Currency Name': 'Mexican Peso', 'Region': 'Mexico'},
        {'Currency Code': 'MYR', 'Currency Name': 'Malaysian Ringgit', 'Region': 'Malaysia'},
        {'Currency Code': 'NOK', 'Currency Name': 'Norwegian Krone', 'Region': 'Norway'},
        {'Currency Code': 'NZD', 'Currency Name': 'New Zealand Dollar', 'Region': 'New Zealand'},
        {'Currency Code': 'PAB', 'Currency Name': 'Panamanian Balboa', 'Region': 'Panama'},
        {'Currency Code': 'PEN', 'Currency Name': 'Peruvian Nuevo Sol', 'Region': 'Peru'},
        {'Currency Code': 'PHP', 'Currency Name': 'Philippine Peso', 'Region': 'Philippines'},
        {'Currency Code': 'PKR', 'Currency Name': 'Pakistani Rupee', 'Region': 'Pakistan'},
        {'Currency Code': 'PLN', 'Currency Name': 'Polish Zloty', 'Region': 'Poland'},
        {'Currency Code': 'PYG', 'Currency Name': 'Paraguayan Guarani', 'Region': 'Paraguay'},
        {'Currency Code': 'RON', 'Currency Name': 'Romanian Leu', 'Region': 'Romania'},
        {'Currency Code': 'RUB', 'Currency Name': 'Russian Ruble', 'Region': 'Russian Federation'},
        {'Currency Code': 'SAR', 'Currency Name': 'Saudi Riyal', 'Region': 'Saudi Arabia'},
        {'Currency Code': 'SEK', 'Currency Name': 'Swedish Krona', 'Region': 'Sweden'},
        {'Currency Code': 'SGD', 'Currency Name': 'Singapore Dollar', 'Region': 'Singapore'},
        {'Currency Code': 'THB', 'Currency Name': 'Thai Baht', 'Region': 'Thailand'},
        {'Currency Code': 'TRY', 'Currency Name': 'Turkish Lira', 'Region': 'Turkey'},
        {'Currency Code': 'TWD', 'Currency Name': 'New Taiwan Dollar', 'Region': 'Taiwan'},
        {'Currency Code': 'UAH', 'Currency Name': 'Ukrainian Hryvnia', 'Region': 'Ukraine'},
        {'Currency Code': 'USD', 'Currency Name': 'US Dollar', 'Region': 'United States'},
        {'Currency Code': 'UYU', 'Currency Name': 'Uruguayan Peso', 'Region': 'Uruguay'},
        {'Currency Code': 'VND', 'Currency Name': 'Vietnamese Dong', 'Region': 'Vietnam'},
        {'Currency Code': 'ZAR', 'Currency Name': 'South African Rand', 'Region': 'South Africa'}]