const exchangeSchema = {
    'Currency Code': String,
    'Currency Name': String,
    Region: String,
    date: Date,
    rates:{
    	AED: Number,
	    ARS: Number,
    	AUD: Number,
	    BGN: Number,
    	BRL: Number,
	    BSD: Number,
	    CAD: Number,
	    CHF: Number,
	    CLP: Number,
	    CNY: Number,
	    COP: Number,
    	CZK: Number,
    	DKK: Number,
	    DOP: Number,
	    EGP: Number,
	    EUR: Number,
	    FJD: Number,
	    GBP: Number,
	    GTQ: Number,
	    HKD: Number,
	    HRK: Number,
	    HUF: Number,
	    IDR: Number,
	    ILS: Number,
	    INR: Number,
	    ISK: Number,
	    JPY: Number,
	    KRW: Number,
	    KZT: Number,
	    MXN: Number,
	    MYR: Number,
	    NOK: Number,
	    NZD: Number,
	    PAB: Number,
	    PEN: Number,
	    PHP: Number,
	    PKR: Number,
	    PLN: Number,
	    PYG: Number,
	    RON: Number,
	    RUB: Number,
	    SAR: Number,
	    SEK: Number,
	    SGD: Number,
	    THB: Number,
	    TRY: Number,
	    TWD: Number,
	    UAH: Number,
	    USD: Number,
	    UYU: Number,
	    VND: Number,
        ZAR: Number
    }
};
exports.module(exchangeSchema);
